FROM maven:3.9.6-eclipse-temurin-17 AS builder
WORKDIR /app

COPY pom.xml .
COPY src ./src
RUN mvn clean package -DskipTests

FROM eclipse-temurin:17-jre
WORKDIR /app

RUN apt-get update \
    && apt-get install -y mysql-client netcat-traditional \
    && rm -rf /var/lib/apt/lists/*

COPY --from=builder /app/target/*.jar app.jar

COPY docker-entrypoint-test.sh /app/docker-entrypoint-test.sh

RUN chmod +x /app/docker-entrypoint-test.sh

EXPOSE 8080

ENTRYPOINT ["/app/docker-entrypoint-test.sh"]
