spring:
  datasource:
    # 注意：生产不应该使用createDatabaseIfNotExist，应该手动建，避免误建误删
    url: jdbc:mysql://localhost:3306/store_api?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
    #    url: jdbc:mysql://localhost:3306/store_api?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: myPassword!
    driver-class-name: com.mysql.cj.jdbc.Driver

    dynamic:
      primary: master
      strict: false
      datasource:
        master:
          # url: jdbc:mysql://localhost:3306/store_api?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
          url: jdbc:mysql://localhost:3306/store_api?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
          username: root
          password: myPassword!
          driver-class-name: com.mysql.cj.jdbc.Driver
          type: com.alibaba.druid.pool.DruidDataSource
        slave1:
          url: jdbc:mysql://localhost:3306/store_api?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
          username: root
          password: myPassword!
          driver-class-name: com.mysql.cj.jdbc.Driver
          type: com.alibaba.druid.pool.DruidDataSource
        slave2:
          url: jdbc:mysql://localhost:3306/store_api?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
          username: root
          password: myPassword!
          driver-class-name: com.mysql.cj.jdbc.Driver
          type: com.alibaba.druid.pool.DruidDataSource

  druid:
    stat-view-servlet:
      enabled: true
      login-username: admin
      login-password: admin
    filter:
      stat:
        log-slow-sql: true
        slow-sql-millis: 1000
        merge-sql: true

  flyway:
    # 注意：生产不应该使用createDatabaseIfNotExist，应该手动建，避免误建误删
    url: jdbc:mysql://localhost:3306/store_api?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
    user: root
    password: myPassword!

  jpa:
    show-sql: true

  data:
    redis:
      cluster:
        nodes:
          - 127.0.0.1:6379
          - 127.0.0.1:6380
          - 127.0.0.1:6381
          - 127.0.0.1:6382
          - 127.0.0.1:6383
          - 127.0.0.1:6384
      # password:  # 如果你的 Redis 有设置密码，填在这里，没有可以注释掉
      timeout: 3000 # 毫秒，连接超时
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
          max-wait: 10000

  rabbitmq:
    # 用户名和密码（默认值是guest，如果你有更改，更新这里的值）
    username: guest
    password: guest
    # 配置多个 RabbitMQ 集群节点地址
    addresses: localhost:5672,localhost:5673,localhost:5674
    # 虚拟主机配置，默认是根虚拟主机 /
    virtual-host: /
    # 连接的端口，RabbitMQ 的默认端口是 5672
    port: 5672
    # 连接池配置（可选）
    connection-timeout: 30000  # 连接超时（单位：毫秒）
    requested-heartbeat: 60    # 请求心跳间隔（单位：秒）
    # 指定集群的 Erlang Cookie，确保集群内所有节点一致
    erlang-cookie: SuperSecretCookie

websiteUrl: http://localhost:4242
swagger:
  server-url: http://localhost:8080
