spring:
  application:
    name: store
  jwt:
    secret: ${JWT_SECRET}
    accessTokenExpiration: 300 # 5m
    refreshTokenExpiration: 604800 # 7d
  profiles:
    active: prod
stripe:
  secretKey: ${STRIPE_SECRET_KEY}
  webhookSecretKey: ${STRIPE_WEBHOOK_SECRET_KEY}
management:
  endpoints:
    web:
      exposure:
        include: "*"  # 或 "health", "info" 等
  endpoint:
    health:
      show-details: always